Starting Hangfire Server using job storage: 'SQL Server: (localdb)\mssqllocaldb@DataBase'
Using the following options for SQL Server job storage: Queue poll interval: 00:00:00.
Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
Execution loop BackgroundServerProcess:4c74d043 has started in 11,458 ms
Server desktop-mpl10nb:404:1d1678c5 successfully announced in 59,365 ms
Execution loop ServerHeartbeatProcess:7ec27877 has started in 28,0757 ms
Server desktop-mpl10nb:404:1d1678c5 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
Execution loop ServerWatchdog:280890e4 has started in 5,851100000000001 ms
Execution loop ServerJobCancellationWatcher:a2ea5a86 has started in 9,9387 ms
Execution loop ExpirationManager:27d2b644 has started in 18,1946 ms
Execution loop CountersAggregator:efa8f7f7 has started in 8,4746 ms
Execution loop Worker:8660487e has started in 15,709700000000002 ms
1 servers were removed due to timeout
Removing outdated records from the 'AggregatedCounter' table...
Aggregating records in 'Counter' table...
Execution loop Worker:26e42d71 has started in 20,3673 ms
Execution loop Worker:9a6f0c83 has started in 28,730700000000002 ms
Execution loop Worker:f6ed7355 has started in 28,6993 ms
Execution loop Worker:a4b90e5f has started in 33,823 ms
Execution loop Worker:b6ac50be has started in 42,566700000000004 ms
Execution loop Worker:5c9c5f9a has started in 49,1068 ms
Execution loop Worker:0b653d57 has started in 49,397000000000006 ms
Execution loop Worker:3899996e has started in 59,5441 ms
Server desktop-mpl10nb:404:1d1678c5 all the dispatchers started
Execution loop Worker:c6f0c1a6 has started in 58,6608 ms
Removing outdated records from the 'Job' table...
Execution loop Worker:a884c8f6 has started in 64,0558 ms
Execution loop Worker:2a3f4291 has started in 71,77550000000001 ms
Execution loop Worker:26f70a09 has started in 82,486 ms
Execution loop Worker:6a2bb5ff has started in 89,41290000000001 ms
Execution loop Worker:8f509e56 has started in 94,4582 ms
Execution loop Worker:963c7658 has started in 101,4252 ms
Execution loop Worker:03188a4e has started in 109,1567 ms
Execution loop Worker:461173e3 has started in 114,23400000000001 ms
Execution loop Worker:8641b87f has started in 122,61640000000001 ms
Execution loop Worker:d6bc7aab has started in 128,3931 ms
Execution loop DelayedJobScheduler:b06025a6 has started in 15,9518 ms
Execution loop RecurringJobScheduler:fb3a4cbf has started in 13,6547 ms
Removing outdated records from the 'List' table...
Removing outdated records from the 'Set' table...
Removing outdated records from the 'Hash' table...
Request starting HTTP/2 GET https://localhost:5001/  
Executing endpoint 'PointSystem.Controllers.HomeController.Index (PointSystem)'
Route matched with {action = "Index", controller = "Home", page = "", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller PointSystem.Controllers.HomeController (PointSystem).
user visited home page
Executing ViewResult, running view Index.
Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executed ViewResult - view Index executed in 387.6411ms.
Executed action PointSystem.Controllers.HomeController.Index (PointSystem) in 436.7781ms
Executed endpoint 'PointSystem.Controllers.HomeController.Index (PointSystem)'
Request finished in 1109.8773ms 200 text/html; charset=utf-8
Request starting HTTP/2 GET https://localhost:5001/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'C:\university\5_sem\ASP_net\Новая папка\PointSystem\PointSystem\wwwroot\favicon.ico'
Request finished in 50.5148ms 200 image/x-icon
Server desktop-mpl10nb:404:1d1678c5 heartbeat successfully sent
Request starting HTTP/2 GET https://localhost:5001/Proposals  
Executing endpoint 'PointSystem.Controllers.ProposalsController.Index (PointSystem)'
Route matched with {action = "Index", controller = "Proposals", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index() on controller PointSystem.Controllers.ProposalsController (PointSystem).
Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [p].[id], [p].[AspNetUserId], [p].[Content], [p].[EndTime], [p].[MaxPeople], [p].[Point], [p].[StartTime], [p].[Status], [p].[Topic], [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
FROM [Proposals] AS [p]
LEFT JOIN [AspNetUsers] AS [a] ON [p].[AspNetUserId] = [a].[Id]
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 295.1419ms.
Executed action PointSystem.Controllers.ProposalsController.Index (PointSystem) in 565.7180000000001ms
Executed endpoint 'PointSystem.Controllers.ProposalsController.Index (PointSystem)'
Request finished in 690.8754ms 200 text/html; charset=utf-8
Request starting HTTP/2 GET https://localhost:5001/Feasts  
Executing endpoint 'PointSystem.Controllers.FeastsController.Index (PointSystem)'
Route matched with {action = "Index", controller = "Feasts", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index() on controller PointSystem.Controllers.FeastsController (PointSystem).
Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [f].[id], [f].[Content], [f].[EndTime], [f].[Location], [f].[StartTime], [f].[Topic]
FROM [Feasts] AS [f]
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 138.89610000000002ms.
Executed action PointSystem.Controllers.FeastsController.Index (PointSystem) in 278.1018ms
Executed endpoint 'PointSystem.Controllers.FeastsController.Index (PointSystem)'
Request finished in 419.3388ms 200 text/html; charset=utf-8
Request starting HTTP/2 GET https://localhost:5001/RegistrationFeasts  
Executing endpoint 'PointSystem.Controllers.RegistrationFeastsController.Index (PointSystem)'
Route matched with {action = "Index", controller = "RegistrationFeasts", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index() on controller PointSystem.Controllers.RegistrationFeastsController (PointSystem).
Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [r].[id], [r].[AspNetUserId], [r].[Content], [r].[EndTime], [r].[FeastId], [r].[Point], [r].[StartTime], [r].[Status], [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName], [f].[id], [f].[Content], [f].[EndTime], [f].[Location], [f].[StartTime], [f].[Topic]
FROM [RegistrationFeasts] AS [r]
LEFT JOIN [AspNetUsers] AS [a] ON [r].[AspNetUserId] = [a].[Id]
INNER JOIN [Feasts] AS [f] ON [r].[FeastId] = [f].[id]
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 355.3311ms.
Executed action PointSystem.Controllers.RegistrationFeastsController.Index (PointSystem) in 615.6664000000001ms
Executed endpoint 'PointSystem.Controllers.RegistrationFeastsController.Index (PointSystem)'
Request finished in 739.3327ms 200 text/html; charset=utf-8
Request starting HTTP/2 GET https://localhost:5001/Proposals  
Executing endpoint 'PointSystem.Controllers.ProposalsController.Index (PointSystem)'
Route matched with {action = "Index", controller = "Proposals", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index() on controller PointSystem.Controllers.ProposalsController (PointSystem).
Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [p].[id], [p].[AspNetUserId], [p].[Content], [p].[EndTime], [p].[MaxPeople], [p].[Point], [p].[StartTime], [p].[Status], [p].[Topic], [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
FROM [Proposals] AS [p]
LEFT JOIN [AspNetUsers] AS [a] ON [p].[AspNetUserId] = [a].[Id]
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 381.2341ms.
Executed action PointSystem.Controllers.ProposalsController.Index (PointSystem) in 515.6991ms
Executed endpoint 'PointSystem.Controllers.ProposalsController.Index (PointSystem)'
Request finished in 655.4354000000001ms 200 text/html; charset=utf-8
An unhandled exception has occurred while executing the request.
Invalid password for user e3844a99-5059-4f16-a392-d1cc1a9c12d4.
User e3844a99-5059-4f16-a392-d1cc1a9c12d4 failed to provide the correct password.
Failed executing DbCommand (18ms) [Parameters=[@__id_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [t].[id], [t].[AspNetUserId], [t].[Content], [t].[EndTime], [t].[MaxPeople], [t].[Point], [t].[StartTime], [t].[Status], [t].[Topic], [t].[Id0], [t].[AccessFailedCount], [t].[ConcurrencyStamp], [t].[Email], [t].[EmailConfirmed], [t].[LockoutEnabled], [t].[LockoutEnd], [t].[NormalizedEmail], [t].[NormalizedUserName], [t].[PasswordHash], [t].[PhoneNumber], [t].[PhoneNumberConfirmed], [t].[SecurityStamp], [t].[TwoFactorEnabled], [t].[UserName], [c].[Id], [c].[AspNetUserId], [c].[Date], [c].[ProposalId], [c].[Text], [c].[UserName]
FROM (
    SELECT TOP(1) [p].[id], [p].[AspNetUserId], [p].[Content], [p].[EndTime], [p].[MaxPeople], [p].[Point], [p].[StartTime], [p].[Status], [p].[Topic], [a].[Id] AS [Id0], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
    FROM [Proposals] AS [p]
    LEFT JOIN [AspNetUsers] AS [a] ON [p].[AspNetUserId] = [a].[Id]
    WHERE ([p].[id] = @__id_0) AND @__id_0 IS NOT NULL
) AS [t]
LEFT JOIN [Commentaries] AS [c] ON [t].[id] = [c].[ProposalId]
ORDER BY [t].[id], [c].[Id]
An exception occurred while iterating over the results of a query for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Commentaries'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:ca800e82-565b-4e9c-b1de-6e3bc70b5afb
Error Number:208,State:1,Class:16
Failed executing DbCommand (15ms) [Parameters=[@__id_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [t].[id], [t].[AspNetUserId], [t].[Content], [t].[EndTime], [t].[MaxPeople], [t].[Point], [t].[StartTime], [t].[Status], [t].[Topic], [t].[Id0], [t].[AccessFailedCount], [t].[ConcurrencyStamp], [t].[Email], [t].[EmailConfirmed], [t].[LockoutEnabled], [t].[LockoutEnd], [t].[NormalizedEmail], [t].[NormalizedUserName], [t].[PasswordHash], [t].[PhoneNumber], [t].[PhoneNumberConfirmed], [t].[SecurityStamp], [t].[TwoFactorEnabled], [t].[UserName], [c].[Id], [c].[AspNetUserId], [c].[Date], [c].[ProposalId], [c].[Text], [c].[UserName]
FROM (
    SELECT TOP(1) [p].[id], [p].[AspNetUserId], [p].[Content], [p].[EndTime], [p].[MaxPeople], [p].[Point], [p].[StartTime], [p].[Status], [p].[Topic], [a].[Id] AS [Id0], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
    FROM [Proposals] AS [p]
    LEFT JOIN [AspNetUsers] AS [a] ON [p].[AspNetUserId] = [a].[Id]
    WHERE ([p].[id] = @__id_0) AND @__id_0 IS NOT NULL
) AS [t]
LEFT JOIN [Commentaries] AS [c] ON [t].[id] = [c].[ProposalId]
ORDER BY [t].[id], [c].[Id]
An exception occurred while iterating over the results of a query for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Commentaries'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:45fe1ab2-8177-4a66-b0b1-75f5be2f5b1c
Error Number:208,State:1,Class:16
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
Failed to invoke hub method 'SendMessage'.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
Failed to process the job '47': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:32.
Failed to process the job '47': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:20.
Failed to process the job '49': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:28.
Failed to process the job '49': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:44.
Failed to process the job '50': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:43.
Failed to process the job '49': an exception occurred. Retry attempt 3 of 10 will be performed in 00:00:34.
Failed to process the job '55': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:44.
Failed to process the job '57': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:23.
An unhandled exception has occurred while executing the request.
Failed to process the job '64': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:38.
Failed to process the job '64': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:34.
Failed to process the job '64': an exception occurred. Retry attempt 3 of 10 will be performed in 00:01:04.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
Failed executing DbCommand (19ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [r].[id], [r].[AspNetUserId], [r].[Content], [r].[EndTime], [r].[FeastId], [r].[Point], [r].[StartTime], [r].[Status], [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName], [f].[id], [f].[Content], [f].[EndTime], [f].[Location], [f].[RediarectFlag], [f].[RediarectUrl], [f].[StartTime], [f].[Topic]
FROM [RegistrationFeasts] AS [r]
LEFT JOIN [AspNetUsers] AS [a] ON [r].[AspNetUserId] = [a].[Id]
INNER JOIN [Feasts] AS [f] ON [r].[FeastId] = [f].[id]
An exception occurred while iterating over the results of a query for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'RediarectFlag'.
Invalid column name 'RediarectUrl'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:67ed34c7-bda8-4fa6-b5b8-a0121b8b0a5b
Error Number:207,State:1,Class:16
An unhandled exception has occurred while executing the request.
User 50145f5a-54d0-461a-bcce-acef55b177bd password validation failed: PasswordRequiresNonAlphanumeric;PasswordRequiresUpper.
User d04c24a8-0a66-4b4b-9c11-98c8bfd60fc6 password validation failed: PasswordRequiresLower;PasswordRequiresUpper.
User e49acfd7-7951-4bb4-b2a1-df1f91fbae8a validation failed: DuplicateUserName.
Failed to process the job '15': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:30.
Failed to process the job '16': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:34.
Failed to process the job '15': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:44.
Failed to process the job '16': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:42.
Failed to process the job '15': an exception occurred. Retry attempt 3 of 10 will be performed in 00:01:31.
Failed to process the job '16': an exception occurred. Retry attempt 3 of 10 will be performed in 00:00:40.
Failed to process the job '16': an exception occurred. Retry attempt 4 of 10 will be performed in 00:03:32.
Failed to process the job '15': an exception occurred. Retry attempt 4 of 10 will be performed in 00:02:16.
Failed to process the job '16': an exception occurred. Retry attempt 5 of 10 will be performed in 00:06:06.
Failed to process the job '15': an exception occurred. Retry attempt 5 of 10 will be performed in 00:06:41.
Failed to process the job '16': an exception occurred. Retry attempt 6 of 10 will be performed in 00:12:10.
An unhandled exception has occurred while executing the request.
User bc2e5ea0-02fb-45b3-ac42-1ec0f7402125 validation failed: DuplicateUserName.
An unhandled exception has occurred while executing the request.
Failed to process the job '15': an exception occurred. Retry attempt 6 of 10 will be performed in 00:11:52.
Failed to process the job '16': an exception occurred. Retry attempt 7 of 10 will be performed in 00:24:25.
User 36b04835-c80e-4429-aa08-7dee81647218 validation failed: DuplicateUserName.
Failed to process the job '15': an exception occurred. Retry attempt 7 of 10 will be performed in 00:22:26.
An unhandled exception has occurred while executing the request.
Failed to process the job '15': an exception occurred. Retry attempt 8 of 10 will be performed in 00:41:12.
Failed to process the job '16': an exception occurred. Retry attempt 8 of 10 will be performed in 00:43:28.
Failed to process the job '15': an exception occurred. Retry attempt 9 of 10 will be performed in 01:09:25.
Failed to process the job '16': an exception occurred. Retry attempt 9 of 10 will be performed in 01:08:49.
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
User c6ce8bc5-45e7-413a-8e3c-f76e25389151 password validation failed: PasswordRequiresLower;PasswordRequiresUpper.
An unhandled exception has occurred while executing the request.
Invalid password for user 5e511804-75b0-45db-a72f-7c6e3239bac1.
User 5e511804-75b0-45db-a72f-7c6e3239bac1 failed to provide the correct password.
Invalid password for user 5e511804-75b0-45db-a72f-7c6e3239bac1.
User 5e511804-75b0-45db-a72f-7c6e3239bac1 failed to provide the correct password.
Failed executing DbCommand (296ms) [Parameters=[@p0='?' (Size = 450), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
DELETE FROM [AspNetUsers]
WHERE [Id] = @p0 AND [ConcurrencyStamp] = @p1;
SELECT @@ROWCOUNT;
An exception occurred in the database while saving changes for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_Proposals_AspNetUsers_AspNetUserId". The conflict occurred in database "DataBase", table "dbo.Proposals", column 'AspNetUserId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:2ffff95b-9d28-4d52-8ee5-72c8910eb71b
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Failed executing DbCommand (22ms) [Parameters=[@p0='?' (Size = 450), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
DELETE FROM [AspNetUsers]
WHERE [Id] = @p0 AND [ConcurrencyStamp] = @p1;
SELECT @@ROWCOUNT;
An exception occurred in the database while saving changes for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_Proposals_AspNetUsers_AspNetUserId". The conflict occurred in database "DataBase", table "dbo.Proposals", column 'AspNetUserId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9939ff14-7640-42a2-8797-ed7b4bdbd794
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Failed executing DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [Feasts] ADD [RediarectFlag] bit NOT NULL DEFAULT CAST(0 AS bit);
An error occurred while applying the migrations for 'PointSystem.Data.ApplicationDbContext'. See InnerException for details:
An unhandled exception has occurred while executing the request.
Failed executing DbCommand (161ms) [Parameters=[@p0='?' (Size = 450), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
DELETE FROM [AspNetUsers]
WHERE [Id] = @p0 AND [ConcurrencyStamp] = @p1;
SELECT @@ROWCOUNT;
An exception occurred in the database while saving changes for context type 'PointSystem.Data.ApplicationDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_Proposals_AspNetUsers_AspNetUserId". The conflict occurred in database "DataBase", table "dbo.Proposals", column 'AspNetUserId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9939ff14-7640-42a2-8797-ed7b4bdbd794
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
An unhandled exception has occurred while executing the request.
An unhandled exception has occurred while executing the request.
Invalid password for user 5e511804-75b0-45db-a72f-7c6e3239bac1.
User 5e511804-75b0-45db-a72f-7c6e3239bac1 failed to provide the correct password.
Failed to process the job '36': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:32.
Failed to process the job '36': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:52.
Failed to process the job '36': an exception occurred. Retry attempt 3 of 10 will be performed in 00:00:49.
